# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProductsApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProductsApp
pod 'Alamofire'
pod 'MaterialActivityIndicator'
pod 'SwiftAlertView'

  target 'ProductsAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProductsAppUITests' do
    # Pods for testing
  end

end
